### ISSUE TITLE
Param filetype for reading nameless phyto_data

### ISSUE THREAD

**Issue by robertladwig** [AquaticEcoDynamics/libaed2#18]
Since 0d76de1 GLM v3.1 doesn't recognize my phytoplankton namelist file (neither NML nor CSV) when starting a simulation. I did test this on Windows 10 Home and macOS Catalina. I always get 
```
         aed2_phytoplankton initialization
 Unknown file type "aed2/aed2_phyto_pars.csv"
STOP Error reading namelist phyto_data
```

Thanks!

**Comment by casper-boon** [comment]
This was fixed in 3.1.1 - sadly only available from our website at :
https://aquatic.science.uwa.edu.au/research/models/GLM/Download/downloader.php?bin&version=3.1
